ALTER TABLE users
ADD COLUMN sessions_played INT NOT NULL DEFAULT 0,
ADD COLUMN sessions_hosted INT NOT NULL DEFAULT 0,
ADD COLUMN rating DECIMAL(3,2) NOT NULL DEFAULT 0,
ADD COLUMN reviews_count INT NOT NULL DEFAULT 0;