// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"mime/multipart"
	"time"

	"github.com/itzLilix/questboard-profile-service/internal/entities"
	"github.com/itzLilix/questboard-profile-service/internal/infrastructure"
	"github.com/itzLilix/questboard-shared/dtos"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateUser(ctx context.Context, user *entities.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockAuthRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockAuthRepository_CreateUser_Call {
	return &MockAuthRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockAuthRepository_CreateUser_Call) Run(run func(ctx context.Context, user *entities.User)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) Return(err error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) DeleteRefreshToken(ctx context.Context, prefix string) error {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockAuthRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockAuthRepository_Expecter) DeleteRefreshToken(ctx interface{}, prefix interface{}) *MockAuthRepository_DeleteRefreshToken_Call {
	return &MockAuthRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, prefix)}
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, prefix string)) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) Return(err error) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, prefix string) error) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByPrefix provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetRefreshTokenByPrefix(ctx context.Context, prefix string) (*entities.RefreshToken, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByPrefix")
	}

	var r0 *entities.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.RefreshToken, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.RefreshToken); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetRefreshTokenByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByPrefix'
type MockAuthRepository_GetRefreshTokenByPrefix_Call struct {
	*mock.Call
}

// GetRefreshTokenByPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockAuthRepository_Expecter) GetRefreshTokenByPrefix(ctx interface{}, prefix interface{}) *MockAuthRepository_GetRefreshTokenByPrefix_Call {
	return &MockAuthRepository_GetRefreshTokenByPrefix_Call{Call: _e.mock.On("GetRefreshTokenByPrefix", ctx, prefix)}
}

func (_c *MockAuthRepository_GetRefreshTokenByPrefix_Call) Run(run func(ctx context.Context, prefix string)) *MockAuthRepository_GetRefreshTokenByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetRefreshTokenByPrefix_Call) Return(refreshToken *entities.RefreshToken, err error) *MockAuthRepository_GetRefreshTokenByPrefix_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepository_GetRefreshTokenByPrefix_Call) RunAndReturn(run func(ctx context.Context, prefix string) (*entities.RefreshToken, error)) *MockAuthRepository_GetRefreshTokenByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUserByEmail(ctx context.Context, email string) (*entities.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockAuthRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockAuthRepository_GetUserByEmail_Call {
	return &MockAuthRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockAuthRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetUserByEmail_Call) Return(user *entities.User, err error) *MockAuthRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entities.User, error)) *MockAuthRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUserByID(ctx context.Context, id string) (*entities.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockAuthRepository_GetUserByID_Call {
	return &MockAuthRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockAuthRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockAuthRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetUserByID_Call) Return(user *entities.User, err error) *MockAuthRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entities.User, error)) *MockAuthRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) SaveRefreshToken(ctx context.Context, token *entities.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockAuthRepository_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *entities.RefreshToken
func (_e *MockAuthRepository_Expecter) SaveRefreshToken(ctx interface{}, token interface{}) *MockAuthRepository_SaveRefreshToken_Call {
	return &MockAuthRepository_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, token)}
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) Run(run func(ctx context.Context, token *entities.RefreshToken)) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entities.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) Return(err error) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_SaveRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token *entities.RefreshToken) error) *MockAuthRepository_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastLogin provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) UpdateLastLogin(ctx context.Context, user *entities.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_UpdateLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastLogin'
type MockAuthRepository_UpdateLastLogin_Call struct {
	*mock.Call
}

// UpdateLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockAuthRepository_Expecter) UpdateLastLogin(ctx interface{}, user interface{}) *MockAuthRepository_UpdateLastLogin_Call {
	return &MockAuthRepository_UpdateLastLogin_Call{Call: _e.mock.On("UpdateLastLogin", ctx, user)}
}

func (_c *MockAuthRepository_UpdateLastLogin_Call) Run(run func(ctx context.Context, user *entities.User)) *MockAuthRepository_UpdateLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_UpdateLastLogin_Call) Return(err error) *MockAuthRepository_UpdateLastLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_UpdateLastLogin_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) error) *MockAuthRepository_UpdateLastLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// Follow provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) Follow(ctx context.Context, followerID string, followedID string) error {
	ret := _mock.Called(ctx, followerID, followedID)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, followerID, followedID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type MockUsersRepository_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID string
//   - followedID string
func (_e *MockUsersRepository_Expecter) Follow(ctx interface{}, followerID interface{}, followedID interface{}) *MockUsersRepository_Follow_Call {
	return &MockUsersRepository_Follow_Call{Call: _e.mock.On("Follow", ctx, followerID, followedID)}
}

func (_c *MockUsersRepository_Follow_Call) Run(run func(ctx context.Context, followerID string, followedID string)) *MockUsersRepository_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_Follow_Call) Return(err error) *MockUsersRepository_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_Follow_Call) RunAndReturn(run func(ctx context.Context, followerID string, followedID string) error) *MockUsersRepository_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// GetBriefsByIDs provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetBriefsByIDs(ctx context.Context, ids []string) ([]dtos.UserBrief, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetBriefsByIDs")
	}

	var r0 []dtos.UserBrief
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]dtos.UserBrief, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []dtos.UserBrief); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.UserBrief)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetBriefsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBriefsByIDs'
type MockUsersRepository_GetBriefsByIDs_Call struct {
	*mock.Call
}

// GetBriefsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockUsersRepository_Expecter) GetBriefsByIDs(ctx interface{}, ids interface{}) *MockUsersRepository_GetBriefsByIDs_Call {
	return &MockUsersRepository_GetBriefsByIDs_Call{Call: _e.mock.On("GetBriefsByIDs", ctx, ids)}
}

func (_c *MockUsersRepository_GetBriefsByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockUsersRepository_GetBriefsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetBriefsByIDs_Call) Return(userBriefs []dtos.UserBrief, err error) *MockUsersRepository_GetBriefsByIDs_Call {
	_c.Call.Return(userBriefs, err)
	return _c
}

func (_c *MockUsersRepository_GetBriefsByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]dtos.UserBrief, error)) *MockUsersRepository_GetBriefsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByID(ctx context.Context, id string) (*entities.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUsersRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUsersRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUsersRepository_GetUserByID_Call {
	return &MockUsersRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUsersRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByID_Call) Return(user *entities.User, err error) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entities.User, error)) *MockUsersRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByUsername(ctx context.Context, username string) (*entities.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUsersRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUsersRepository_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockUsersRepository_GetUserByUsername_Call {
	return &MockUsersRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Return(user *entities.User, err error) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*entities.User, error)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserIDByUsername provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserIDByUsername(ctx context.Context, username string) (string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDByUsername")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserIDByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDByUsername'
type MockUsersRepository_GetUserIDByUsername_Call struct {
	*mock.Call
}

// GetUserIDByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUsersRepository_Expecter) GetUserIDByUsername(ctx interface{}, username interface{}) *MockUsersRepository_GetUserIDByUsername_Call {
	return &MockUsersRepository_GetUserIDByUsername_Call{Call: _e.mock.On("GetUserIDByUsername", ctx, username)}
}

func (_c *MockUsersRepository_GetUserIDByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUsersRepository_GetUserIDByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserIDByUsername_Call) Return(s string, err error) *MockUsersRepository_GetUserIDByUsername_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUsersRepository_GetUserIDByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (string, error)) *MockUsersRepository_GetUserIDByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// IsFollowing provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) IsFollowing(ctx context.Context, followerID string, followedID string) (bool, error) {
	ret := _mock.Called(ctx, followerID, followedID)

	if len(ret) == 0 {
		panic("no return value specified for IsFollowing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, followerID, followedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, followerID, followedID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, followerID, followedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_IsFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFollowing'
type MockUsersRepository_IsFollowing_Call struct {
	*mock.Call
}

// IsFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID string
//   - followedID string
func (_e *MockUsersRepository_Expecter) IsFollowing(ctx interface{}, followerID interface{}, followedID interface{}) *MockUsersRepository_IsFollowing_Call {
	return &MockUsersRepository_IsFollowing_Call{Call: _e.mock.On("IsFollowing", ctx, followerID, followedID)}
}

func (_c *MockUsersRepository_IsFollowing_Call) Run(run func(ctx context.Context, followerID string, followedID string)) *MockUsersRepository_IsFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_IsFollowing_Call) Return(b bool, err error) *MockUsersRepository_IsFollowing_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUsersRepository_IsFollowing_Call) RunAndReturn(run func(ctx context.Context, followerID string, followedID string) (bool, error)) *MockUsersRepository_IsFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) Unfollow(ctx context.Context, followerID string, followedID string) error {
	ret := _mock.Called(ctx, followerID, followedID)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, followerID, followedID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type MockUsersRepository_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID string
//   - followedID string
func (_e *MockUsersRepository_Expecter) Unfollow(ctx interface{}, followerID interface{}, followedID interface{}) *MockUsersRepository_Unfollow_Call {
	return &MockUsersRepository_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, followerID, followedID)}
}

func (_c *MockUsersRepository_Unfollow_Call) Run(run func(ctx context.Context, followerID string, followedID string)) *MockUsersRepository_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_Unfollow_Call) Return(err error) *MockUsersRepository_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_Unfollow_Call) RunAndReturn(run func(ctx context.Context, followerID string, followedID string) error) *MockUsersRepository_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStats provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) UpdateStats(ctx context.Context, statName dtos.UserStatName, values map[string]int) error {
	ret := _mock.Called(ctx, statName, values)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStats")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.UserStatName, map[string]int) error); ok {
		r0 = returnFunc(ctx, statName, values)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_UpdateStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStats'
type MockUsersRepository_UpdateStats_Call struct {
	*mock.Call
}

// UpdateStats is a helper method to define mock.On call
//   - ctx context.Context
//   - statName dtos.UserStatName
//   - values map[string]int
func (_e *MockUsersRepository_Expecter) UpdateStats(ctx interface{}, statName interface{}, values interface{}) *MockUsersRepository_UpdateStats_Call {
	return &MockUsersRepository_UpdateStats_Call{Call: _e.mock.On("UpdateStats", ctx, statName, values)}
}

func (_c *MockUsersRepository_UpdateStats_Call) Run(run func(ctx context.Context, statName dtos.UserStatName, values map[string]int)) *MockUsersRepository_UpdateStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.UserStatName
		if args[1] != nil {
			arg1 = args[1].(dtos.UserStatName)
		}
		var arg2 map[string]int
		if args[2] != nil {
			arg2 = args[2].(map[string]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_UpdateStats_Call) Return(err error) *MockUsersRepository_UpdateStats_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_UpdateStats_Call) RunAndReturn(run func(ctx context.Context, statName dtos.UserStatName, values map[string]int) error) *MockUsersRepository_UpdateStats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) UpdateUser(ctx context.Context, input *infrastructure.UpdateUserParams) (*entities.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrastructure.UpdateUserParams) (*entities.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrastructure.UpdateUserParams) *entities.User); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *infrastructure.UpdateUserParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsersRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input *infrastructure.UpdateUserParams
func (_e *MockUsersRepository_Expecter) UpdateUser(ctx interface{}, input interface{}) *MockUsersRepository_UpdateUser_Call {
	return &MockUsersRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, input)}
}

func (_c *MockUsersRepository_UpdateUser_Call) Run(run func(ctx context.Context, input *infrastructure.UpdateUserParams)) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *infrastructure.UpdateUserParams
		if args[1] != nil {
			arg1 = args[1].(*infrastructure.UpdateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_UpdateUser_Call) Return(user *entities.User, err error) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, input *infrastructure.UpdateUserParams) (*entities.User, error)) *MockUsersRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

type MockCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogRepository) EXPECT() *MockCatalogRepository_Expecter {
	return &MockCatalogRepository_Expecter{mock: &_m.Mock}
}

// GetUserIDByUsername provides a mock function for the type MockCatalogRepository
func (_mock *MockCatalogRepository) GetUserIDByUsername(ctx context.Context, username string) (string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDByUsername")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogRepository_GetUserIDByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDByUsername'
type MockCatalogRepository_GetUserIDByUsername_Call struct {
	*mock.Call
}

// GetUserIDByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockCatalogRepository_Expecter) GetUserIDByUsername(ctx interface{}, username interface{}) *MockCatalogRepository_GetUserIDByUsername_Call {
	return &MockCatalogRepository_GetUserIDByUsername_Call{Call: _e.mock.On("GetUserIDByUsername", ctx, username)}
}

func (_c *MockCatalogRepository_GetUserIDByUsername_Call) Run(run func(ctx context.Context, username string)) *MockCatalogRepository_GetUserIDByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCatalogRepository_GetUserIDByUsername_Call) Return(s string, err error) *MockCatalogRepository_GetUserIDByUsername_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCatalogRepository_GetUserIDByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (string, error)) *MockCatalogRepository_GetUserIDByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersList provides a mock function for the type MockCatalogRepository
func (_mock *MockCatalogRepository) GetUsersList(ctx context.Context, filter *infrastructure.UserCatalogFilter, viewerID string) ([]infrastructure.UserCardRow, string, error) {
	ret := _mock.Called(ctx, filter, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersList")
	}

	var r0 []infrastructure.UserCardRow
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrastructure.UserCatalogFilter, string) ([]infrastructure.UserCardRow, string, error)); ok {
		return returnFunc(ctx, filter, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrastructure.UserCatalogFilter, string) []infrastructure.UserCardRow); ok {
		r0 = returnFunc(ctx, filter, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]infrastructure.UserCardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *infrastructure.UserCatalogFilter, string) string); ok {
		r1 = returnFunc(ctx, filter, viewerID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *infrastructure.UserCatalogFilter, string) error); ok {
		r2 = returnFunc(ctx, filter, viewerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCatalogRepository_GetUsersList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersList'
type MockCatalogRepository_GetUsersList_Call struct {
	*mock.Call
}

// GetUsersList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *infrastructure.UserCatalogFilter
//   - viewerID string
func (_e *MockCatalogRepository_Expecter) GetUsersList(ctx interface{}, filter interface{}, viewerID interface{}) *MockCatalogRepository_GetUsersList_Call {
	return &MockCatalogRepository_GetUsersList_Call{Call: _e.mock.On("GetUsersList", ctx, filter, viewerID)}
}

func (_c *MockCatalogRepository_GetUsersList_Call) Run(run func(ctx context.Context, filter *infrastructure.UserCatalogFilter, viewerID string)) *MockCatalogRepository_GetUsersList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *infrastructure.UserCatalogFilter
		if args[1] != nil {
			arg1 = args[1].(*infrastructure.UserCatalogFilter)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCatalogRepository_GetUsersList_Call) Return(userCardRows []infrastructure.UserCardRow, s string, err error) *MockCatalogRepository_GetUsersList_Call {
	_c.Call.Return(userCardRows, s, err)
	return _c
}

func (_c *MockCatalogRepository_GetUsersList_Call) RunAndReturn(run func(ctx context.Context, filter *infrastructure.UserCatalogFilter, viewerID string) ([]infrastructure.UserCardRow, string, error)) *MockCatalogRepository_GetUsersList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GenerateAccessToken(userID string, role dtos.Role) (string, error) {
	ret := _mock.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, dtos.Role) (string, error)); ok {
		return returnFunc(userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, dtos.Role) string); ok {
		r0 = returnFunc(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, dtos.Role) error); ok {
		r1 = returnFunc(userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenProvider_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID string
//   - role dtos.Role
func (_e *MockTokenProvider_Expecter) GenerateAccessToken(userID interface{}, role interface{}) *MockTokenProvider_GenerateAccessToken_Call {
	return &MockTokenProvider_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, role)}
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) Run(run func(userID string, role dtos.Role)) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 dtos.Role
		if args[1] != nil {
			arg1 = args[1].(dtos.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) Return(s string, err error) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) RunAndReturn(run func(userID string, role dtos.Role) (string, error)) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseToken(tokenString string) (*dtos.TokenClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *dtos.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*dtos.TokenClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *dtos.TokenClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockTokenProvider_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenProvider_Expecter) ParseToken(tokenString interface{}) *MockTokenProvider_ParseToken_Call {
	return &MockTokenProvider_ParseToken_Call{Call: _e.mock.On("ParseToken", tokenString)}
}

func (_c *MockTokenProvider_ParseToken_Call) Run(run func(tokenString string)) *MockTokenProvider_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseToken_Call) Return(tokenClaims *dtos.TokenClaims, err error) *MockTokenProvider_ParseToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *MockTokenProvider_ParseToken_Call) RunAndReturn(run func(tokenString string) (*dtos.TokenClaims, error)) *MockTokenProvider_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenManager creates a new instance of MockRefreshTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenManager {
	mock := &MockRefreshTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenManager is an autogenerated mock type for the RefreshTokenManager type
type MockRefreshTokenManager struct {
	mock.Mock
}

type MockRefreshTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenManager) EXPECT() *MockRefreshTokenManager_Expecter {
	return &MockRefreshTokenManager_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockRefreshTokenManager
func (_mock *MockRefreshTokenManager) Generate() (string, string, time.Time, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, time.Time, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() time.Time); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(time.Time)
	}
	if returnFunc, ok := ret.Get(3).(func() error); ok {
		r3 = returnFunc()
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockRefreshTokenManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockRefreshTokenManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockRefreshTokenManager_Expecter) Generate() *MockRefreshTokenManager_Generate_Call {
	return &MockRefreshTokenManager_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockRefreshTokenManager_Generate_Call) Run(run func()) *MockRefreshTokenManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRefreshTokenManager_Generate_Call) Return(s string, s1 string, time1 time.Time, err error) *MockRefreshTokenManager_Generate_Call {
	_c.Call.Return(s, s1, time1, err)
	return _c
}

func (_c *MockRefreshTokenManager_Generate_Call) RunAndReturn(run func() (string, string, time.Time, error)) *MockRefreshTokenManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// IsValid provides a mock function for the type MockRefreshTokenManager
func (_mock *MockRefreshTokenManager) IsValid(clientToken string, storedTokenHash string) bool {
	ret := _mock.Called(clientToken, storedTokenHash)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(clientToken, storedTokenHash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRefreshTokenManager_IsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValid'
type MockRefreshTokenManager_IsValid_Call struct {
	*mock.Call
}

// IsValid is a helper method to define mock.On call
//   - clientToken string
//   - storedTokenHash string
func (_e *MockRefreshTokenManager_Expecter) IsValid(clientToken interface{}, storedTokenHash interface{}) *MockRefreshTokenManager_IsValid_Call {
	return &MockRefreshTokenManager_IsValid_Call{Call: _e.mock.On("IsValid", clientToken, storedTokenHash)}
}

func (_c *MockRefreshTokenManager_IsValid_Call) Run(run func(clientToken string, storedTokenHash string)) *MockRefreshTokenManager_IsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenManager_IsValid_Call) Return(b bool) *MockRefreshTokenManager_IsValid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRefreshTokenManager_IsValid_Call) RunAndReturn(run func(clientToken string, storedTokenHash string) bool) *MockRefreshTokenManager_IsValid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) CompareHashAndPassword(hash string, password string) error {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordHasher_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type MockPasswordHasher_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockPasswordHasher_Expecter) CompareHashAndPassword(hash interface{}, password interface{}) *MockPasswordHasher_CompareHashAndPassword_Call {
	return &MockPasswordHasher_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hash, password)}
}

func (_c *MockPasswordHasher_CompareHashAndPassword_Call) Run(run func(hash string, password string)) *MockPasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_CompareHashAndPassword_Call) Return(err error) *MockPasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordHasher_CompareHashAndPassword_Call) RunAndReturn(run func(hash string, password string) error) *MockPasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordHasher_Expecter) HashPassword(password interface{}) *MockPasswordHasher_HashPassword_Call {
	return &MockPasswordHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordHasher_HashPassword_Call) Run(run func(password string)) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_HashPassword_Call) Return(s string, err error) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordHasher_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageUploader creates a new instance of MockImageUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageUploader {
	mock := &MockImageUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageUploader is an autogenerated mock type for the ImageUploader type
type MockImageUploader struct {
	mock.Mock
}

type MockImageUploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageUploader) EXPECT() *MockImageUploader_Expecter {
	return &MockImageUploader_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockImageUploader
func (_mock *MockImageUploader) Upload(file *multipart.FileHeader, subdir string) (string, error) {
	ret := _mock.Called(file, subdir)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*multipart.FileHeader, string) (string, error)); ok {
		return returnFunc(file, subdir)
	}
	if returnFunc, ok := ret.Get(0).(func(*multipart.FileHeader, string) string); ok {
		r0 = returnFunc(file, subdir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*multipart.FileHeader, string) error); ok {
		r1 = returnFunc(file, subdir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageUploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockImageUploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - file *multipart.FileHeader
//   - subdir string
func (_e *MockImageUploader_Expecter) Upload(file interface{}, subdir interface{}) *MockImageUploader_Upload_Call {
	return &MockImageUploader_Upload_Call{Call: _e.mock.On("Upload", file, subdir)}
}

func (_c *MockImageUploader_Upload_Call) Run(run func(file *multipart.FileHeader, subdir string)) *MockImageUploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *multipart.FileHeader
		if args[0] != nil {
			arg0 = args[0].(*multipart.FileHeader)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageUploader_Upload_Call) Return(s string, err error) *MockImageUploader_Upload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockImageUploader_Upload_Call) RunAndReturn(run func(file *multipart.FileHeader, subdir string) (string, error)) *MockImageUploader_Upload_Call {
	_c.Call.Return(run)
	return _c
}
